apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner-search.my-apps.tap.20240610043917.0.0+build.6aff574
spec:
  refName: where-for-dinner-search.my-apps.tap
  version: 20240610043917.0.0+build.6aff574
  releaseNotes: |
    Release v20240610043917.0.0+build.6aff574 of package where-for-dinner-search.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: gcr.io/tap-ci/ci-pipeline/apps-09-06-2024-18-18-41-963235828/where-for-dinner-search-my-apps-bundle@sha256:ce191c101b64ef659df1e4e8b911e67d8ad7e5858d75b6bc99a5df0b05c51065
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""
          minLength: 1

