apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner.my-apps.tap.20240610043850.0.0+build.6aff574
spec:
  refName: where-for-dinner.my-apps.tap
  version: 20240610043850.0.0+build.6aff574
  releaseNotes: |
    Release v20240610043850.0.0+build.6aff574 of package where-for-dinner.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: gcr.io/tap-ci/ci-pipeline/apps-09-06-2024-18-18-41-963235828/where-for-dinner-my-apps-bundle@sha256:eb4ec2e41fcf4931209f7ece59f9652e23ace21642e76cff183367a4f2cfd091
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""
          minLength: 1

